kind: pipeline
type: docker
name: default

steps:

- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive --remote --merge

- name: build
  image: grimkriegor/voidworks-forge
  commands:
  - cd examples/debugclient/
  - mkdir -p build
  - cd build
  - cmake ..
  - make
